### ISSUE TITLE
RuntimeWarning: coroutine 'sleep' was never awaited

### ISSUE THREAD

**Issue by FloPinguin** [aahnik/telegram-chat-forward#17]
```shell
A wait of 2060 seconds is required (caused by SendMessageRequest)
forwarder.py:64: RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(delay=fwe.seconds)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

A wait of 2058 seconds is required (caused by SendMessageRequest)
A wait of 2058 seconds is required (caused by SendMessageRequest)
...
A wait of 2057 seconds is required (caused by SendMessageRequest)
A wait of 2057 seconds is required (caused by SendMessageRequest)
...
A wait of 2052 seconds is required (caused by SendMediaRequest)
A wait of 2052 seconds is required (caused by SendMessageRequest)

2021-02-18 16:40:06,400 - root - INFO - Completed working with name
2021-02-18 16:40:06,406 - telethon.client.uploads - INFO - Uploading file of 53 bytes in 1 chunks of 131072
2021-02-18 16:40:06,588 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.175.56:443/TcpFull...
2021-02-18 16:40:06,589 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.175.56:443/TcpFull complete!
Traceback (most recent call last):
  File "forwarder.py", line 83, in <module>
    asyncio.run(forward_job())
  File "F:\Program Files\Python\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "F:\Program Files\Python\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "forwarder.py", line 72, in forward_job
    await client.send_file('me', 'config.ini', caption='This is your config file for telegram-chat-forward.')
  File "F:\Program Files\Python\lib\site-packages\telethon\client\uploads.py", line 382, in send_file
    return self._get_response_message(request, await self(request), entity)
  File "F:\Program Files\Python\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "F:\Program Files\Python\lib\site-packages\telethon\client\users.py", line 50, in _call
    raise errors.FloodWaitError(request=r, capture=diff)
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 2052 seconds is required (caused by SendMediaRequest)
```

**Comment by aahnik** [comment]
Thank you @FloPinguin for reporting this. This was caused by my mistake. I have fixed that. 

Please update the code, and try again, hopefully this has been resolved.
