### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by onofriosalvatici** [aahnik/telegram-chat-forward#34]
I receive this message when running forwarder.py

Traceback (most recent call last):
File "/Users/myusername/Desktop/telegram-chat-forward/forwarder.py", line 77, in
assert forwards
AssertionError

What could it be? Thank you!

**Comment by JessimAz** [comment]
Hello,
I also got a similar message after running the script for the 3rd time

Traceback (most recent call last):
File "forwarder.py", line 6, in <module>
from telethon.tl.patched import MessageService
ModuleNotFoundError: No module named 'telethon'
